server:
  port: 8888

spring:
  application:
    name: Spring-Cloud-Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/example/config-repo
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
